src/Entity/Flights.php
<?php

namespace App\Entity;

use App\Repository\FlightsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FlightsRepository::class)]
class Flights
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 6)]
    private ?string $num_flight = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $hour_start = null;

    #[ORM\ManyToOne(inversedBy: 'city_start')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cities $city_start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $hour_end = null;

    #[ORM\ManyToOne(inversedBy: 'city_end')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cities $city_end = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?bool $reduc = null;

    #[ORM\Column]
    private ?int $total_seats = null;

    public function __construct() {
        $this->num_flight = $this->nbrAleatoireFlight();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumFlight(): ?string
    {
        return $this->num_flight;
    }

    public function setNumFlight(string $num_flight): static
    {
        $this->num_flight = $num_flight;

        return $this;
    }

    public function getHourStart(): ?\DateTimeInterface
    {
        return $this->hour_start;
    }

    public function setHourStart(\DateTimeInterface $hour_start): static
    {
        $this->hour_start = $hour_start;

        return $this;
    }

    public function getCityStart(): ?Cities
    {
        return $this->city_start;
    }

    public function setCityStart(?Cities $city_start): static
    {
        $this->city_start = $city_start;

        return $this;
    }

    public function getHourEnd(): ?\DateTimeInterface
    {
        return $this->hour_end;
    }

    public function setHourEnd(\DateTimeInterface $hour_end): static
    {
        $this->hour_end = $hour_end;

        return $this;
    }

    public function getCityEnd(): ?Cities
    {
        return $this->city_end;
    }

    public function setCityEnd(?Cities $city_end): static
    {
        $this->city_end = $city_end;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isReduc(): ?bool
    {
        return $this->reduc;
    }

    public function setReduc(bool $reduc): static
    {
        $this->reduc = $reduc;

        return $this;
    }

    public function getTotalSeats(): ?int
    {
        return $this->total_seats;
    }

    public function setTotalSeats(int $total_seats): static
    {
        $this->total_seats = $total_seats;

        return $this;
    }

    public function nbrAleatoireFlight() {
        // Génère 2 lettres aléatoires
        $letters = chr(rand(65,90)).chr(rand(65,90));
        $numbers = rand(1000, 9999);
        return $letters.$numbers;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\FlightsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(FlightsRepository $flightsRepository): Response
    {
        $flights = $flightsRepository->findAll();
        return $this->render('main/index.html.twig', [
            'flights' => $flights,
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des vols{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="col-8">Liste des vols</h1>
    
        {% if app.user %}
        <a type="button" class="btn btn-info col-4" href="{{ path('app_logout')}}">Se déconnecter</a>
        {% else %}
        <a type="button" class="btn btn-info col-2" href="{{ path('app_register')}}">S'inscrire</a>
        <a type="button" class="btn btn-info col-2" href="{{ path('app_login')}}">Se connecter</a>
        {% endif %}

    </div>
   
   
    <div class="form-group">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Numéro de vol</th>
                    <th scope="col">Ville de départ</th>
                    <th scope="col">Ville d'arrivée</th>
                    <th scope="col">Jour de départ</th>
                    <th scope="col">Heure de départ</th>
                    <th scope="col">Jour d'arrivée</th>
                    <th scope="col">Heure d'arrivée</th>
                    <th scope="col">Places</th>
                    <th scope="col">Prix</th>
                    <th scope="col">Réduction</th>
                </tr>
            </thead>
           
            <tbody>
                {% for flight in flights %}
                <tr>
                    <td>{{ flight.numFlight }}</td>
                    <td>{{ flight.cityStart.name }}</td>
                    <td>{{ flight.cityEnd.name }}</td>
                    <td>{{ flight.hourStart|date('F-dS') }}</td>
                    <td>{{ flight.hourStart|date('H:i') }}</td>
                    <td>{{ flight.hourEnd|date('F-dS') }}</td>
                    <td>{{ flight.hourEnd|date('H:i') }}</td>
                    <td>{{ flight.totalSeats }}</td>
                    <td>{{ flight.price }}</td>
                    {% if flight.reduc == true %}
                    <td><img src="/icones/insigne-de-reduction.png" alt="réduction"></td>
                    {% endif %}
                </tr>
                 {% endfor %}
            </tbody>
        </table>
        {% if is_granted('ROLE_ADMIN') %}
        <div class="mx-auto">
            <a type="button" class="btn btn-success" href="{{ path('app_flights_new') }}">Ajouter un nouveau vol</a>
            <a type="button" class="btn btn-success" href="{{ path('app_cities_new') }}">Ajouter une nouvelle ville</a>
            <a type="button" class="btn btn-info" href="{{ path('app_flights_index') }}">Page Administration</a>
        </div>
        {% endif %}
        
    </div>
</div>
    
{% endblock %}